/**
 * Single source of truth for all SustainSutra services. Both the homepage
 * ServiceMatrix and the ServicesLandingPage import from here to avoid
 * divergent hardcoded arrays.
 *
 * `icon` is a lucide-react icon component name (string) — the consumer maps
 * it to the actual component. This keeps the constant framework-agnostic.
 */
export const SERVICES = [
    {
        id: 'carbon-footprinting',
        title: 'Carbon Footprinting',
        short: 'Precise Scope 1, 2 & 3 GHG inventories aligned with ISO 14064.',
        description: 'Engineering high-precision GHG inventories across Scope 1, 2, and 3 to establish science-based decarbonization baselines.',
        icon: 'BarChart3',
        href: '/services/carbon-footprinting',
        category: 'Advisory',
    },
    {
        id: 'ghg-mapping',
        title: 'GHG Mapping',
        short: 'Strategic source identification and boundary setting.',
        description: 'Strategic source identification and boundary setting to ensure complete transparency in organizational emissions accounting.',
        icon: 'Globe',
        href: '/services/ghg-mapping',
        category: 'Accounting',
    },
    {
        id: 'esg-strategy',
        title: 'ESG Strategy',
        short: 'Double materiality and board-level strategic alignment.',
        description: 'Transforming sustainability into institutional value through double materiality and board-level strategic alignment.',
        icon: 'Layers',
        href: '/services/esg-strategy',
        category: 'Strategic',
    },
    {
        id: 'brsr-reporting',
        title: 'BRSR Reporting',
        short: 'End-to-end SEBI compliance and audit-ready disclosures.',
        description: 'End-to-end SEBI compliance support for top-listed entities, ensuring robust and audit-ready sustainability disclosures.',
        icon: 'FileSpreadsheet',
        href: '/services/brsr-reporting',
        category: 'Compliance',
    },
    {
        id: 'iso-verification',
        title: 'ISO Verification & Testing',
        short: 'Independent ISO 14064 assurance and technical testing.',
        description: 'Independent third-party assurance of carbon data according to ISO 14064, backed by technical testing and analysis services.',
        icon: 'ShieldCheck',
        href: '/services/iso-verification',
        category: 'Assurance',
    },
    {
        id: 'training',
        title: 'Academy & Training',
        short: 'Upskilling teams on GRI, SASB, and Net-Zero methodologies.',
        description: 'Upskilling executive and operational teams on global standards like GRI, SASB, and Net-Zero methodologies.',
        icon: 'GraduationCap',
        href: '/services/training-capacity',
        category: 'Capacity Building',
    },
    {
        id: 'energy-audits',
        title: 'Energy Audits',
        short: 'Efficiency assessments and cost-saving decarbonization.',
        description: 'Technical assessments to identify efficiency gaps and implement cost-saving decarbonization measures.',
        icon: 'Zap',
        href: '/services/energy-audits',
        category: 'Technical',
    },
    {
        id: 'water-wastewater',
        title: 'Water & Wastewater',
        short: 'Water audits, effluent treatment, and stewardship.',
        description: 'Water audits, wastewater management, and catchment-level water stewardship aligned with ISO 46001 and the AWS Standard.',
        icon: 'Droplet',
        href: '/services/water-wastewater',
        category: 'Technical',
    },
    {
        id: 'waste-management',
        title: 'Waste Management',
        short: 'Solid, plastic & e-waste strategy toward zero landfill.',
        description: 'Strategic waste management consulting covering solid, plastic, and e-waste — minimizing generation and maximizing resource recovery.',
        icon: 'Trash2',
        href: '/services/waste-management',
        category: 'Advisory',
    },
    {
        id: 'epr',
        title: 'EPR & Regulatory Compliance',
        short: 'Extended Producer Responsibility and environmental law.',
        description: 'Extended Producer Responsibility compliance and environmental law advisory — registrations, targets, filings, and audits.',
        icon: 'Scale',
        href: '/services/epr',
        category: 'Compliance',
    },
    {
        id: 'carbon-markets',
        title: 'Carbon Markets & Climate Finance',
        short: 'Credit development, CCTS strategy, and monetization.',
        description: 'Carbon markets and climate finance advisory — CCTS compliance, voluntary credit development, Article 6 access, and green capital structuring.',
        icon: 'TrendingUp',
        href: '/services/carbon-markets',
        category: 'Strategic',
    },
    {
        id: 'cleaner-production',
        title: 'Cleaner Production',
        short: 'Process redesign for emissions and cost reduction.',
        description: 'Cleaner production assessments that redesign industrial processes to cut emissions, waste, and operating cost simultaneously.',
        icon: 'Factory',
        href: '/services/cleaner-production',
        category: 'Operations',
    },
    {
        id: 'circular-economy',
        title: 'Circular Economy',
        short: 'Redesigning value chains into restorative systems.',
        description: 'Redesigning linear value chains into restorative systems that maximize resource utility and minimize waste.',
        icon: 'RefreshCw',
        href: '/services/circular-economy',
        category: 'Innovation',
    },
    {
        id: 'resource-efficiency',
        title: 'Resource Efficiency',
        short: 'Optimizing water, energy, and material throughput.',
        description: 'Optimizing water, energy, and material throughput to build operational resilience in a resource-constrained world.',
        icon: 'Droplet',
        href: '/services/resource-efficiency',
        category: 'Operations',
    },
];
