import React, { useState } from 'react';
import { Helmet } from 'react-helmet';
import { motion, AnimatePresence } from 'framer-motion';
import { Search } from 'lucide-react';

const SustainabilityGlossaryPage = () => {
    const [searchTerm, setSearchTerm] = useState('');

    const glossaryTerms = [
        {
            term: "Biodiversity",
            definition: "The variety of plant and animal life in the world or in a particular habitat, a high level of which is usually considered to be important and desirable."
        },
        {
            term: "Carbon Footprint",
            definition: "The total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions."
        },
        {
            term: "Circular Economy",
            definition: "A model of production and consumption, which involves sharing, leasing, reusing, repairing, refurbishing and recycling existing materials and products as long as possible."
        },
        {
            term: "Decarbonization",
            definition: "The reduction or removal of carbon dioxide from energy sources."
        },
        {
            term: "ESG (Environmental, Social, and Governance)",
            definition: "A set of standards for a company's operations that socially conscious investors use to screen potential investments."
        },
        {
            term: "Greenhouse Gas (GHG)",
            definition: "A gas that contributes to the greenhouse effect by absorbing infrared radiation, e.g., carbon dioxide and chlorofluorocarbons."
        },
        {
            term: "Greenwashing",
            definition: "The practice of making misleading or unsubstantiated claims about the environmental benefits of a product, service, technology, or company practice."
        },
        {
            term: "GRI (Global Reporting Initiative)",
            definition: "An international independent standards organization that helps businesses, governments and other organizations understand and communicate their impacts on issues such as climate change, human rights and corruption."
        },
        {
            term: "Net Zero",
            definition: "Cutting greenhouse gas emissions to as close to zero as possible, with any remaining emissions re-absorbed from the atmosphere, by oceans and forests for instance."
        },
        {
            term: "Scope 1 Emissions",
            definition: "Direct emissions from owned or controlled sources."
        },
        {
            term: "Scope 2 Emissions",
            definition: "Indirect emissions from the generation of purchased energy."
        },
        {
            term: "Scope 3 Emissions",
            definition: "All indirect emissions (not included in scope 2) that occur in the value chain of the reporting company, including both upstream and downstream emissions."
        },
        {
            term: "SDGs (Sustainable Development Goals)",
            definition: "A collection of 17 interlinked global goals designed to be a 'blueprint to achieve a better and more sustainable future for all'."
        },
        {
            term: "Sustainability",
            definition: "Meeting the needs of the present without compromising the ability of future generations to meet their own needs."
        },
        {
            term: "TCFD (Task Force on Climate-related Financial Disclosures)",
            definition: "An organization established by the Financial Stability Board to develop recommendations for more effective climate-related disclosures that could promote more informed investment, credit, and insurance underwriting decisions."
        }
    ];

    const filteredTerms = glossaryTerms.filter(item =>
        item.term.toLowerCase().includes(searchTerm.toLowerCase()) ||
        item.definition.toLowerCase().includes(searchTerm.toLowerCase())
    ).sort((a, b) => a.term.localeCompare(b.term));

    return (
        <>
            <Helmet>
                <title>Sustainability Glossary | SustainSutra</title>
                <meta name="description" content="Definitions of key sustainability terms, acronyms, and frameworks." />
            </Helmet>

            <div className="min-h-screen bg-navy text-offwhite font-ibm pt-32 pb-16">
                <div className="container mx-auto px-4 max-w-4xl">
                    <div className="text-center mb-12">
                        <h1 className="text-4xl md:text-5xl font-playfair mb-6">Sustainability Glossary</h1>
                        <p className="text-xl text-dimmed mb-8">
                            Decode the complex language of ESG and sustainability.
                        </p>

                        <div className="relative max-w-xl mx-auto">
                            <input
                                type="text"
                                placeholder="Search definitions..."
                                value={searchTerm}
                                onChange={(e) => setSearchTerm(e.target.value)}
                                className="w-full py-4 pl-12 pr-4 bg-white/5 border border-white/10 rounded-xl text-offwhite focus:outline-none focus:border-gold/50 transition-colors"
                            />
                            <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 text-dimmed" size={20} />
                        </div>
                    </div>

                    <div className="space-y-4">
                        <AnimatePresence>
                            {filteredTerms.map((item, idx) => (
                                <motion.div
                                    key={item.term}
                                    initial={{ opacity: 0, y: 10 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    exit={{ opacity: 0, scale: 0.95 }}
                                    transition={{ delay: idx * 0.05 }}
                                    className="glassmorphism p-6 rounded-xl hover:bg-white/5 transition-colors"
                                >
                                    <h3 className="text-xl font-bold text-gold mb-2">{item.term}</h3>
                                    <p className="text-dimmed leading-relaxed">{item.definition}</p>
                                </motion.div>
                            ))}
                        </AnimatePresence>

                        {filteredTerms.length === 0 && (
                            <div className="text-center py-12 text-dimmed">
                                No terms found matching "{searchTerm}"
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </>
    );
};

export default SustainabilityGlossaryPage;
