import React, { useState, useMemo } from 'react';
import { Helmet } from 'react-helmet';
import { motion, AnimatePresence } from 'framer-motion';
import { Search, Info, ArrowUpRight, BookOpen } from 'lucide-react';

const SustainabilityGlossaryPage = () => {
    const [searchTerm, setSearchTerm] = useState('');
    const [selectedLetter, setSelectedLetter] = useState('ALL');

    const glossaryTerms = [
        { term: "Adaptation", definition: "Adjustments in ecological, social, or economic systems in response to actual or expected climatic stimuli and their effects or impacts." },
        { term: "Additionality", definition: "The requirement that a carbon project's greenhouse gas reductions or removals would not have occurred anyway in a 'business as usual' scenario." },
        { term: "Annexure IV", definition: "The technical guidelines under the Carbon Credit Trading Scheme (CCTS) specifying mandatory monitoring and reporting requirements for obligated entities in India." },
        { term: "BRSR (Business Responsibility and Sustainability Reporting)", definition: "SEBI's mandatory reporting framework for the top 1000 listed entities in India, focusing on ESG performance across nine principles." },
        { term: "Biodiversity", definition: "The variety of plant and animal life in the world or in a particular habitat, a high level of which is usually considered to be important and desirable for ecological balance." },
        { term: "Blue Carbon", definition: "The carbon captured and stored by the world's ocean and coastal ecosystems, particularly mangroves, seagrasses, and salt marshes." },
        { term: "CCC (Carbon Credit Certificate)", definition: "A certificate issued to an obligated entity that achieves emission reductions beyond its assigned target under the CCTS, representing one tonne of CO2 equivalent (tCO2e) reduced." },
        { term: "CCTS (Carbon Credit Trading Scheme)", definition: "India's institutional framework for establishing a domestic carbon market to incentivize greenhouse gas emission reductions through the trading of Carbon Credit Certificates." },
        { term: "CDP (Carbon Disclosure Project)", definition: "A global non-profit that runs the world's leading environmental disclosure system for companies, cities, states, and regions." },
        { term: "CO2e (Carbon Dioxide Equivalent)", definition: "A universal unit of measurement to indicate the global warming potential of each greenhouse gas, expressed in terms of the GWP of one unit of carbon dioxide." },
        { term: "Carbon Footprint", definition: "The total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions, measured in units of carbon dioxide equivalent." },
        { term: "Carbon Leakage", definition: "When companies move production to countries with less stringent climate policies, potentially leading to an increase in total global emissions." },
        { term: "Carbon Sequestration", definition: "The process of capturing and storing atmospheric carbon dioxide, either through biological means (like forests and soil) or technological means (like Carbon Capture and Storage)." },
        { term: "CBAM (Carbon Border Adjustment Mechanism)", definition: "The EU's landmark tool to put a fair price on the carbon emitted during the production of carbon-intensive goods entering the EU." },
        { term: "Circular Economy", definition: "A model of production and consumption which involves sharing, leasing, reusing, repairing, refurbishing and recycling existing materials and products as long as possible." },
        { term: "Decarbonization", definition: "The process of reducing carbon intensity by lowering the amount of greenhouse gas emissions produced by the combustion of fossil fuels." },
        { term: "Double Materiality", definition: "The requirement for companies to report on both how sustainability issues affect their business and how their business impacts people and the environment." },
        { term: "ESG (Environmental, Social, and Governance)", definition: "A set of standards for a company's operations that socially conscious investors use to screen potential investments and evaluate corporate behavior." },
        { term: "EUA (Emission Unit Allowance)", definition: "The standard unit of allowance in emission trading systems, typically representing the right to emit one tonne of carbon dioxide." },
        { term: "Fugitive Emissions", definition: "Intentional or unintentional release of greenhouse gases from anthropogenic activities such as processing, transmission, and storage of fossil fuels." },
        { term: "GHG Protocol", definition: "The most widely used international accounting tool for government and business leaders to understand, quantify, and manage greenhouse gas emissions." },
        { term: "GWP (Global Warming Potential)", definition: "A measure of how much heat a greenhouse gas traps in the atmosphere up to a specific time horizon, relative to carbon dioxide." },
        { term: "Green Bonds", definition: "Fixed-income instruments specifically earmarked to raise money for climate and environmental projects." },
        { term: "Greenhouse Gas (GHG)", definition: "Gases that trap heat in the atmosphere, including Carbon Dioxide (CO2), Methane (CH4), Nitrous Oxide (N2O), and Fluorinated gases." },
        { term: "Greenwashing", definition: "The practice of making misleading or unsubstantiated claims about the environmental benefits of a product, service, or company practice to appear more sustainable than it is." },
        { term: "GRI (Global Reporting Initiative)", definition: "An international standards organization that helps businesses and governments understand and communicate their impact on critical sustainability issues." },
        { term: "ISSB (International Sustainability Standards Board)", definition: "A body created to develop a comprehensive global baseline of high-quality sustainability disclosure standards for financial markets." },
        { term: "Just Transition", definition: "A framework developed by the trade union movement to encompass a range of social interventions needed to secure workers' rights and livelihoods when economies are shifting to sustainable production." },
        { term: "Life Cycle Assessment (LCA)", definition: "A methodology for assessing environmental impacts associated with all the stages of a product's life, from raw material extraction to disposal or recycling." },
        { term: "LULUCF (Land Use, Land-Use Change and Forestry)", definition: "A defined sector under the UNFCCC that covers emissions and removals of greenhouse gases resulting from direct human-induced land use." },
        { term: "Mitigation", definition: "Efforts to reduce or prevent emission of greenhouse gases; can include using new technologies and renewable energies, or changing management practices or consumer behavior." },
        { term: "Natural Capital", definition: "The world's stocks of natural assets which include geology, soil, air, water and all living things." },
        { term: "Net Zero", definition: "A state in which the greenhouse gases going into the atmosphere are balanced by removal out of the atmosphere, resulting in zero net increase in emissions." },
        { term: "Paris Agreement", definition: "A legally binding international treaty on climate change adopted in 2015, aiming to limit global warming to well below 2, preferably to 1.5 degrees Celsius." },
        { term: "Physical Risk", definition: "Risks resulting from climate change that can be event-driven (acute) or longer-term shifts (chronic) in climate patterns." },
        { term: "RECs (Renewable Energy Certificates)", definition: "Market-based instruments that represent the property rights to the environmental and social attributes of renewable electricity generation." },
        { term: "SBTi (Science Based Targets initiative)", definition: "A partnership that provides companies with a clearly defined path to reduce emissions in line with the Paris Agreement goals." },
        { term: "Scope 1 Emissions", definition: "Direct greenhouse gas emissions that occur from sources that are owned or controlled by the company (e.g., emissions from combustion in owned boilers, vehicles)." },
        { term: "Scope 2 Emissions", definition: "Indirect greenhouse gas emissions from the generation of purchased electricity, steam, heating, or cooling consumed by the company." },
        { term: "Scope 3 Emissions", definition: "All other indirect emissions that occur in a company’s value chain, including both upstream and downstream activities (e.g., supply chain, product use)." },
        { term: "SDGs (Sustainable Development Goals)", definition: "A collection of 17 interlinked global goals designed to be a 'blueprint to achieve a better and more sustainable future for all' by 2030." },
        { term: "SFDR (Sustainable Finance Disclosure Regulation)", definition: "An EU regulation introduced to improve transparency in the market for sustainable investment products and to prevent greenwashing." },
        { term: "Sustainability", definition: "The ability to exist constantly; in business, it refers to meeting present needs without compromising the ability of future generations to meet theirs." },
        { term: "TCFD (Task Force on Climate-related Financial Disclosures)", definition: "A framework for more effective climate-related disclosures that promote more informed investment, credit, and insurance underwriting decisions." },
        { term: "TNFD (Taskforce on Nature-related Financial Disclosures)", definition: "A risk management and disclosure framework for organizations to report and act on evolving nature-related risks." },
        { term: "Transition Risk", definition: "The risk inherent in the shift toward a lower-carbon economy, including policy and legal risks, technology risks, market risks, and reputation risks." },
        { term: "Triple Bottom Line", definition: "An accounting framework that incorporates three dimensions of performance: social (people), environmental (planet), and financial (profit)." },
        { term: "VCM (Voluntary Carbon Market)", definition: "A decentralized market where private actors voluntarily buy and sell carbon credits that represent certified removals or reductions of GHGs." },
        { term: "Water Footprint", definition: "The total volume of fresh water used to produce the goods and services consumed by an individual, community, or business." }
    ];

    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');

    const filteredTerms = useMemo(() => {
        return glossaryTerms
            .filter(item => {
                const matchesSearch = item.term.toLowerCase().includes(searchTerm.toLowerCase()) ||
                    item.definition.toLowerCase().includes(searchTerm.toLowerCase());
                const matchesLetter = selectedLetter === 'ALL' || item.term.startsWith(selectedLetter);
                return matchesSearch && matchesLetter;
            })
            .sort((a, b) => a.term.localeCompare(b.term));
    }, [searchTerm, selectedLetter]);

    return (
        <div className="min-h-screen bg-[#0A0F14] text-offwhite selection:bg-gold/30">
            <Helmet>
                <title>Sustainability Glossary | SustainSutra</title>
                <meta name="description" content="Detailed definitions of key sustainability terms, carbon accounting acronyms, and global ESG frameworks." />
            </Helmet>

            {/* Hero Section */}
            <section className="relative pt-16 pb-20 overflow-hidden">
                <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-[500px] bg-gold/5 blur-[120px] rounded-full pointer-events-none" />

                <div className="container relative z-10 mx-auto px-4 text-center">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="inline-flex items-center gap-2 px-4 py-2 bg-gold/10 border border-gold/20 rounded-full mb-8"
                    >
                        <BookOpen className="text-gold" size={16} />
                        <span className="text-gold text-xs font-bold uppercase tracking-widest">Knowledge Base</span>
                    </motion.div>

                    <motion.h1
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.1 }}
                        className="text-5xl md:text-7xl font-playfair mb-6"
                    >
                        Sustainability <span className="text-gold italic">Glossary</span>
                    </motion.h1>

                    <motion.p
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.2 }}
                        className="text-xl text-dimmed max-w-2xl mx-auto mb-12"
                    >
                        Master the terminology of the green transition. From Carbon Credits to Circular Economy, we decode the language of ESG.
                    </motion.p>

                    {/* Interactive Search Bar */}
                    <motion.div
                        initial={{ opacity: 0, scale: 0.95 }}
                        animate={{ opacity: 1, scale: 1 }}
                        transition={{ delay: 0.3 }}
                        className="relative max-w-2xl mx-auto"
                    >
                        <div className="relative group">
                            <div className="absolute inset-0 bg-gold/20 blur-xl group-focus-within:bg-gold/30 transition-all opacity-50" />
                            <input
                                type="text"
                                placeholder="Search by term or definition..."
                                value={searchTerm}
                                onChange={(e) => setSearchTerm(e.target.value)}
                                className="relative w-full py-5 pl-14 pr-6 bg-navy/80 border border-white/10 rounded-2xl text-offwhite placeholder:text-dimmed focus:outline-none focus:border-gold/50 backdrop-blur-xl transition-all text-lg"
                            />
                            <Search className="absolute left-5 top-1/2 -translate-y-1/2 text-gold group-focus-within:scale-110 transition-transform" size={24} />
                        </div>
                    </motion.div>
                </div>
            </section>

            {/* Alphabet Filter */}
            <section className="sticky top-[80px] z-40 py-4 bg-[#0A0F14]/80 backdrop-blur-md border-y border-white/5">
                <div className="container mx-auto px-4">
                    <div className="flex flex-wrap justify-center gap-2">
                        <button
                            onClick={() => setSelectedLetter('ALL')}
                            className={`px-4 py-2 rounded-lg text-sm font-bold transition-all ${selectedLetter === 'ALL' ? 'bg-gold text-navy shadow-lg shadow-gold/20' : 'hover:bg-white/5 text-dimmed'}`}
                        >
                            ALL
                        </button>
                        {alphabet.map(letter => (
                            <button
                                key={letter}
                                onClick={() => setSelectedLetter(letter)}
                                className={`w-10 h-10 flex items-center justify-center rounded-lg text-sm font-bold transition-all ${selectedLetter === letter ? 'bg-gold text-navy shadow-lg shadow-gold/20' : 'hover:bg-white/5 text-dimmed'}`}
                            >
                                {letter}
                            </button>
                        ))}
                    </div>
                </div>
            </section>

            {/* Results Grid */}
            <section className="py-20">
                <div className="container mx-auto px-4 max-w-5xl">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <AnimatePresence mode="popLayout">
                            {filteredTerms.map((item, idx) => (
                                <motion.div
                                    key={item.term}
                                    layout
                                    initial={{ opacity: 0, y: 20 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    exit={{ opacity: 0, scale: 0.95 }}
                                    transition={{ duration: 0.4, delay: idx * 0.02 }}
                                    className="group relative"
                                >
                                    <div className="h-full glassmorphism p-8 rounded-2xl border border-white/5 group-hover:border-gold/30 group-hover:bg-white/[0.03] transition-all overflow-hidden">
                                        {/* Decorative Icon */}
                                        <div className="absolute -top-4 -right-4 w-24 h-24 bg-gold/5 blur-2xl group-hover:bg-gold/10 transition-all rounded-full" />

                                        <div className="relative z-10 flex justify-between items-start mb-4">
                                            <h3 className="text-2xl font-playfair font-bold text-offwhite group-hover:text-gold transition-colors">{item.term}</h3>
                                            <ArrowUpRight className="text-white/10 group-hover:text-gold transition-colors" size={24} />
                                        </div>

                                        <p className="relative z-10 text-dimmed leading-relaxed group-hover:text-offwhite/90 transition-colors">
                                            {item.definition}
                                        </p>

                                        <div className="relative z-10 mt-6 pt-6 border-t border-white/5 flex items-center gap-2 text-gold/60 text-xs font-bold uppercase tracking-widest">
                                            <Info size={14} />
                                            Key ESG Terminology
                                        </div>
                                    </div>
                                </motion.div>
                            ))}
                        </AnimatePresence>
                    </div>

                    {filteredTerms.length === 0 && (
                        <motion.div
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            className="text-center py-32"
                        >
                            <div className="w-20 h-20 bg-white/5 rounded-full flex items-center justify-center mx-auto mb-6">
                                <Search className="text-dimmed" size={32} />
                            </div>
                            <h2 className="text-2xl font-playfair text-offwhite mb-2">No matching terms found</h2>
                            <p className="text-dimmed mb-8">Try adjusting your search or filters.</p>
                            <button
                                onClick={() => { setSearchTerm(''); setSelectedLetter('ALL'); }}
                                className="text-gold font-bold underline underline-offset-4 hover:text-white transition-colors"
                            >
                                Clear all filters
                            </button>
                        </motion.div>
                    )}
                </div>
            </section>

            {/* Quick Navigation Footer */}
            <section className="py-20 bg-gradient-to-t from-gold/5 to-transparent">
                <div className="container mx-auto px-4 text-center">
                    <p className="text-dimmed mb-8">Looking for more detailed guidance?</p>
                    <div className="flex flex-wrap justify-center gap-6">
                        <a href="/insights" className="flex items-center gap-2 text-offwhite font-bold hover:text-gold transition-colors">
                            Technical Articles <ArrowUpRight size={18} />
                        </a>
                        <a href="/regulatory-updates" className="flex items-center gap-2 text-offwhite font-bold hover:text-gold transition-colors">
                            Policy Trackers <ArrowUpRight size={18} />
                        </a>
                    </div>
                </div>
            </section>
        </div>
    );
};

export default SustainabilityGlossaryPage;
